name: CI
on:
  push:
    branches: ['**']
    paths-ignore: ['*.adoc']
  pull_request:
  schedule:
  - cron: '30 2 * * TUE'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: |
        npm run lint
        if [ -n "$(npm --silent run format && git --no-pager diff --name-only)" ]; then
          echo 'Detected pending code style changes'
          exit 1
        fi
    - name: Run tests with coverage
      run: npm run coverage-strict
